sequenceDiagram
   participant browser
   participant server


   browser->>server: POST https://studies.cs.helsinki/exampleapp/new_note
   activate server
   server-->>browser: HTTP status code 302
   %% The server instructs the browser to make a new request to the address located inside the response header section under location "/exampleapp/notes.
   Note over browser, server: URL redirect ask the browser to perform a new HTTP GET request.
   deactivate server

   browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
   activate server
   server-->>browser: HTML document
   Note over browser, server: The browser reloads notes page
   deactivate server

   browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
   activate server
   server-->>browser: CSS file
   deactivate server

   browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
   activate server
   server-->>browser: JavaScript file
   deactivate server

   browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
   activate server
   server-->>browser: [{"content": "Hola madridista", "date": "2024-06-24"}]
   deactivate server
   Note  left of browser: The logic on the server using DOM-API adds the new note.
   %% The code on the server using the DOM-API add the new note to the document.

