%% Exercises 0.5
%% Single page app diagram

sequenceDiagram
participant browser
participant server


browser->>server: GET htps://studies.cs.helsinki.fi/exampleapp/spa
activate server
server-->>browser: HTML document
deactivate server
%% The browser fetches the HTML document which it parse the embedded css file, and the JavaScript which will handle the logic inside the browser.

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
activate server
server-->>browser: CSS file
deactivate server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
activate server
server-->>browser: JavaScript file
deactivate server
Note over browser, server: All the logic for interactivity is done inside the browser.

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
activate server
server-->>browser: JSON file
deactivate server